spring:
  application:
    name: spring-cloud-producer

server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: producer1

test:
  id: 1

