
server:
  port: 9001

spring:
  application:
    name: spring-cloud-consumer

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: consumer1
feign:
  hystrix:
    enabled: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
