server:
  port: 7001

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StSahana/config-repo/          # 配置git仓库的地址
          search-paths: .                                      # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:  root                                       # git仓库的账号
          password:  xxxxxxxxx                           # git仓库的密码！上传代码时检查有无信息泄露

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: consumer2